config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :pieces do
    resources :reviews
  end
  resources :votes, only: [:create], defaults: { format: 'json' }

  root "pieces#index"
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  paginates_per 10
  belongs_to :user
  has_many :reviews

  validates :title, presence: true, uniqueness:
  { scope: :composer, message: "There should only be one title and composer pair" }
  validates :composer, presence: true
  validates :user_id, presence: { message: " must be signed in to create a new piece" }
  validates :url, presence: true, format: { with: URI.regexp }

  # def self.title_search(query)
  #   where("title ilike ?", "%#{query}%")
  # end
  #
  # def self.composer_search(query)
  #   where("composer ilike ?", "%#{query}%")
  # end

  include PgSearch
  pg_search_scope :search_by_keywords,
    against: [:title, :composer],
    using: {
      tsearch: {
        prefix: true
      }
    }

  def editable_by?(user)
    self.user == user
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :authenticate_user!, only: [:update, :edit, :destroy]
  before_action :signed_in_flash, only: [:new]

  def new
    @piece = Piece.new
  end

  def index
    if params[:keyword_search]
      @pieces = Piece.search_by_keywords(params[:keyword_search]).order(:created_at).page(params[:page]).per(10)
    else
      @pieces = Piece.order(:created_at).page(params[:page]).per(10)
    end
  end

  def show
    @piece = Piece.find(params[:id])
    @youtube_url = YouTubeAddy.extract_video_id(@piece.url)
    @review = Review.new
    @reviews = @piece.reviews
    @piece_rating = @reviews.empty? ? 0 : calculate_piece_rating(@reviews)
  end

  def edit
    @piece = Piece.find(params[:id])
    edit_only_piece_created
  end

  def update
    @piece = Piece.find(params[:id])

    if @piece.update_attributes(piece_params)
      flash[:notice] = "Piece edited successfully"
      redirect_to piece_path(@piece)
    else
      flash[:errors] = @piece.errors.full_messages.join(". ")
      render :edit
    end
  end

  def create
    @piece = Piece.new(piece_params)
    @piece.user = current_user
    if @piece.save
      flash[:notice] = "Piece added successfully"
      redirect_to piece_path(@piece)
    else
      flash.now[:errors] = @piece.errors.full_messages.join(". ")
      render :new
    end
  end

  def destroy
    Piece.find(params[:id]).destroy
    flash[:success] = "Piece Deleted"
    redirect_to root_path
  end

  private




  def signed_in_flash
    if !user_signed_in?
      flash[:notice] = "Please sign in to add a piece"
      redirect_to pieces_path
    end
  end

  def edit_only_piece_created
    unless current_user.can_edit?(@piece)
      flash[:notice] = "You can only edit a piece you created"
      redirect_to piece_path(@piece)
    end
  end

  def piece_params
    params.require(:piece).permit(:title, :composer, :url)
  end
end

app/views/pieces/_form.html.haml
= form_for(@piece) do |f|
  %div.review-form-title
    = f.label :url
    = f.text_field :url, placeholder: "YouTube URL"

  %div.review-form-title
    = f.label :title
    = f.text_field :title, placeholder: "Title"

  %div.review-form-title
    = f.label :composer
    = f.text_field :composer, placeholder: "Composer"

  .form-actions
    = f.button "Add Piece"

app/views/pieces/edit.html.haml
%h1 Edit Piece
= form_for(@piece) do |f|
  %div
    = f.label :title
    = f.text_field :title, placeholder: "Title"

  %div
    = f.label :composer
    = f.text_field :composer, placeholder: "Composer"

  .actions
    = f.submit "Edit"
%div= link_to 'Back', pieces_path

app/views/pieces/index.html.haml
.pieces
  - if !@pieces.empty?
    - @pieces.each do |piece|
      = link_to piece_path(piece) do
        .piece
          %p.piece-title= piece.title
          %p.piece-composer= piece.composer

    %hr.line
    = paginate @pieces
  - else
    %h2 No results found

app/views/pieces/new.html.haml
%h1 Add New Music
%div.review-container= render 'form'
%div= link_to 'Back', pieces_path

app/views/pieces/show.html.haml
- provide(:title, 'Show')
.video-container
  .embed-container
    %iframe{width: "560", height: "315", src: "https://www.youtube.com/embed/#{@youtube_url}"}
.show-container
  %h1.show-title#show-title1= @piece.title
  %h5.show-composer= @piece.composer
  .average_rating_star_image
    - whole = image_tag("star-on.png")
    - half = image_tag("star-half.png")
    - off = image_tag("star-off.png")
    - if @piece_rating >= 9.5
      = whole+whole+whole+whole+whole
    - elsif @piece_rating >= 8.5
      = whole+whole+whole+whole+half
    - elsif @piece_rating >= 7.5
      = whole+whole+whole+whole+off
    - elsif @piece_rating >= 6.5
      = whole+whole+whole+half+off
    - elsif @piece_rating >= 5.5
      = whole+whole+whole+off+off
    - elsif @piece_rating >= 4.5
      = whole+whole+half+off+off
    - elsif @piece_rating >= 3.5
      = whole+whole+off+off+off
    - elsif @piece_rating >= 2.5
      = whole+half+off+off+off
    - elsif @piece_rating >= 1.5
      = whole+off+off+off+off
    - elsif @piece_rating > 0.0
      = half+off+off+off+off
    - elsif @piece_rating == 0.0
      = off+off+off+off+off
    - if @reviews.length == 1
      = "#{@reviews.length} user review"
    - else
      = "#{@reviews.length} user reviews"

  %p= "Added by #{@piece.user.username}"

- if user_signed_in?
  - if current_user.can_edit?(@piece)
    .links
      %p= link_to "Edit Piece", edit_piece_path(@piece)
      - if current_user.admin
        %p= link_to "Delete Piece", @piece, method: :delete

.review-form-div
  = render 'reviews/form'

- if !@reviews.nil?
  = render @reviews