config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :pieces do
    resources :reviews
  end
  resources :votes, only: [:create], defaults: { format: 'json' }

  root "pieces#index"
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ActionController::Base
  protect_from_forgery with: :null_session

  def create
    review = Review.new(review_params)
    if review.save
      render json: :nothing, status: :created, location: api_v1_reviews_path(review)
    else
      render json: :nothing, status: :not_found
    end
  end

  private
  def review_params
    params.require(:review).permit(:title, :body, :rating, :user_id, :piece_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:update, :edit, :destroy]
  before_action :piece, only: [:new, :create, :edit, :update, :destroy]
  before_action :only_edit_review_created, only: [:edit]
  before_action :only_update_review_created, only: [:update]

  def new
    @review = Review.new
  end

  def create
    @review = @piece.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      ReviewMailer.new_review(@review).deliver_later
      flash[:notice] = 'Your review has been successfully added.'
      redirect_to piece_path(@piece)
    else
      flash[:notice] = @review.errors.messages.values.join(". ")
      @piece = Piece.find(@review.piece_id)
      @reviews = @piece.reviews
      @piece_rating = @reviews.empty? ? 0 : calculate_piece_rating(@reviews)
      render :'pieces/show'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    review.destroy
    flash[:success] = "Review Deleted"
    redirect_to piece_path(piece)
  end

  private

  def only_edit_review_created
    unless current_user.can_edit?(review)
      flash[:notice] = "You can only edit a review you created"
      redirect_to piece_path(@piece)
    end
  end

  def only_update_review_created
    if review.update_attributes(review_params)
      flash[:notice] = "Review edited successfully"
      redirect_to piece_path(@piece)
    else
      flash[:errors] = @review.errors.full_messages.join(". ")
      render :edit
    end
  end

  def review_params
    params.require(:review).permit(:title, :rating, :body)
  end

  def review
    @review ||= Review.find(params[:id])
  end

  def piece
    @piece ||= Piece.find(params[:piece_id])
  end
end

app/views/reviews/_form.html.haml
- if yield(:title) == "Edit"
  %h1 Edit Review

= form_for [@piece, @review] do |f|
  %div.review-form-title
    = f.collection_radio_buttons(:rating, [[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]], :first, :last)

  %div.review-form-title
    = f.label :title
    = f.text_field :title, placeholder: "Title"

  %div.review-form-title
    = f.label :body
    = f.text_area :body, placeholder: "Review"

  - if yield(:title) == "Show"
    .actions
      = f.submit "Add Review"
  - else
    .actions
      = f.submit "Edit"
      %div= link_to 'Back', piece_path(@piece)

app/views/reviews/_review.html.haml
- if review.title.present?
  .small-12.clearfix.review-container{ id: "review_id-#{review.id}" }
    .voting.small-2{ review_id: "#{review.id}" }
      - if user_signed_in?
        - current_vote = current_user.votes.where(review: review).first
      - if current_vote.nil? || current_vote.up == 0
        %span.nil_vote{ change_up_to: "1" }= link_to "+", votes_path(vote: { review_id: review.id, up: 1 }), method: :post
        %span.nil_vote{ change_up_to: "-1" }= link_to "-", votes_path(vote: { review_id: review.id, up: -1 }), method: :post
      - elsif current_vote.up == 1
        %span.voted{ change_up_to: "0" }= link_to "+", votes_path(vote: { review_id: review.id, up: 0 }), method: :post
        %span.nil_vote{ change_up_to: "-1" }= link_to "-", votes_path(vote: { review_id: review.id, up: -1} ), method: :post
      - elsif current_vote.up == -1
        %span.nil_vote{ change_up_to: "1" }= link_to "+", votes_path(vote: { review_id: review.id, up: 1 }), method: :post
        %span.voted{ change_up_to: "0" }= link_to "-", votes_path(vote: { review_id: review.id, up: 0 }), method: :post

    .review-title-container.small-8
      %h3.review-rating.small-2
        - whole = image_tag("star-on.png")
        - half = image_tag("star-half.png")
        - off = image_tag("star-off.png")
        - if review.rating > 9
          = whole+whole+whole+whole+whole
        - elsif review.rating > 8
          = whole+whole+whole+whole+half
        - elsif review.rating > 7
          = whole+whole+whole+whole+off
        - elsif review.rating > 6
          = whole+whole+whole+half+off
        - elsif review.rating > 5
          = whole+whole+whole+off+off
        - elsif review.rating > 4
          = whole+whole+half+off+off
        - elsif review.rating > 3
          = whole+whole+off+off+off
        - elsif review.rating > 2
          = whole+half+off+off+off
        - elsif review.rating > 1
          = whole+off+off+off+off
        - elsif review.rating > 0
          = half+off+off+off+off

      %h5.review-title.small-7= review.title
      %p.small-10= review.body
      %p.small-12= review.user.username
      - unless current_user.nil?
        - if current_user.can_edit?(review)
          .links
            %p= link_to "Edit Review", edit_piece_review_path(@piece, review)
            %p= link_to "Delete Review", piece_review_path(@piece, review), method: :delete

app/views/reviews/edit.html.haml
- provide(:title, 'Edit')

= render 'form'