config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :pieces do
    resources :reviews
  end
  resources :votes, only: [:create], defaults: { format: 'json' }

  root "pieces#index"
end

app/views/layouts/_search.html.haml
= form_tag(pieces_path, method: :get, id: "search-form") do
  .search_field= text_field_tag :keyword_search, params[:keyword_search], placeholder: "Search by Keywords"
  .search_button= submit_tag "Search", :name => nil, label: "Keyword Search", id: "keyword_search_button"

app/views/layouts/_topbar.html.erb
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name
      %h1= link_to "Shostacodech", root_path
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Right Nav Section
    %ul.right
      %li.active
        %a{:href => "#"} Right Button Active
      %li.has-dropdown
        %a{:href => "#"} My Account
        %ul.dropdown
          %li
            %a{:href => "#"} First link in dropdown
          %li.active
            %a{:href => "#"} Active link in dropdown
    / Left Nav Section
    %ul.left
      %li
        %a{:href => "#"} Left Nav Button

app/views/layouts/_topbar.html.haml
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name

      %h1#shostakodech
        %a.home{:href => root_path} Shostakodech

    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Right Nav Section
    %ul.right
      %li= render 'layouts/search_button'
      %li= render 'layouts/search'
      %li.active
        - if user_signed_in?
          %a{ href: "users/#{current_user.id}", id: "#{current_user.id}", class: "username" }= "Signed in as #{current_user.username}"
          %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          %li.has-dropdown
            %a{:href => "#"} Account
            %ul.dropdown
              %li= link_to 'Sign In', new_user_session_path
              %li.active= link_to 'Sign Up', new_user_registration_path
    %ul.left
      %li= link_to "Add New Piece", new_piece_path

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

    %body
      .topbar= render 'layouts/topbar'
      - flash.each do |type, message|
        .flash= message
      %nav

    .content= yield

    .small-12= render 'layouts/footer'